= AsciiDoc Guide
:author: John Smith

== Document Attributes
Set in a document, usually just below header. https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes-ref/[Details here]

----
:author: John Smith
:email: john@smith.com
:doctype: article | book | inline | manpage
:toc: auto | left | right | macro | preamble
:toc-title: Contents
:toclevels: 3 (1-5)
:revnumber: 0.9
:revdate: 31st July 2021
:revremark: Draft
:experimental:
:imagedir: .\images
:numbered:
:keywords: comma, separated, list, will, appear, in html keywords
:description: adds a meta \
description that will appear in html header \
use backslash to span many lines
----

== The Basics

=== Headers

----
= Document Title (Level 0)

PREAMBLE : Any text between Document title and first Level 1 header appears in
a larger font, it's termed a `leadrole` you can use the attribute [.lead] to
promote any paragraph or you can disable it in the preamble by using [.normal]

== Level 1 Section Title  // Level 1 will get a <hr> below it

=== Level 2 Section Title

==== Level 3 Section Title

===== Level 4 Section Title

====== Level 5 Section Title

== Another Level 1 Section Title
----

=== Paragraphs
Separated by blank lines

----
We were somewhere around Barstow on the edge of the desert when the drugs began
to take hold. I remember saying something like "I feel a bit lightheaded; maybe
you should drive...." 

And suddenly there was a terrible roar all around us and
the sky was full of what looked like huge bats, all swooping and screeching and
diving around the car, which was going about a hundred miles an hour with the
top down to Las Vegas.
----

Renders as

We were somewhere around Barstow on the edge of the desert when the drugs began
to take hold. I remember saying something like "I feel a bit lightheaded; maybe
you should drive...."

And suddenly there was a terrible roar all around us and
the sky was full of what looked like huge bats, all swooping and screeching and
diving around the car, which was going about a hundred miles an hour with the
top down to Las Vegas.

==== Hard line breaks

----
Rubies are red, +
Topazes are blue.
----

Or use the hardbreaks option

----
[%hardbreaks]
Ruby is red.
Java is beige.
----

==== Paragraph Justification
Use `text-<alignment>` where alignment can be `left`, `center`, `right`, `justify`

----
[.text-justify]
We were somewhere around Barstow on the edge of the desert when the drugs began
to take hold. I remember saying something like "I feel a bit lightheaded; maybe
you should drive...."

----

==== Thematic Breaks
----
''' | --- | - - - | *** | * * *
----

==== Page Breaks

----
<<<
----

=== Text Formatting

==== Text Formatting

[%header,cols="2,.^2",width=100%]             
|===                                
|Item | Description                 

a|----
*Bold*
---- 
| *Bold*

a|----
Par**bold** is a place in Lancashire
----
| Par**bold** is a place in Lancashire

a|----
_Italic_
----
| _Italic_

a|----
The word __Italic__ized scores 22 points in scrabble
----
| The word __Italic__ized scores 22 points in scrabble

a|----
`Monospace`
----
| `Monospace`

a|----
Moon Space is an anagram of ``Monospace``
----
| Moon Space is an anagram of ``Monospace``

a|----
You can monospace attributes like this `+{author}+`
----
a| You can monospace attributes like this `+{author}+`

a|----
Compare with `{author}`
----
| Compare with `{author}`

a|----
This text is #highlighted#
----
| This text is #highlighted#

a|----
Subscript : H~2~O
----
| Subscript : H~2~O

a|----
Superscript : E=mc^2^
----
| Superscript : E=mc^2^

|===

==== Text Decoration

[%header,cols="2,.^2",width=100%]
|===
|Item | Description

a|----
[.underline]#underline me#
----
| [.underline]#underline me#

a|----
[.overline]#overline me#
----
| [.overline]#overline me#

a|----
[.line-through]#strike through#
----
| [.line-through]#strike through#

a|----
[.nobreak]#An un broken string of text as a long line of text that will never be split#
----
| [.nobreak]#An un broken string of text as a long line of text that will never be split#

a|----
[.nowrap]#Do not wrap this text#
----
| [.nowrap]#Do not wrap this text#

a|----
[.pre-wrap]#All spaces are preserved       s#
----
| [.pre-wrap]#All spaces are preserved       s#
|===

=== Text Symbols

[%header,cols="2,.^2",width=100%]
|===
|Item | Description

a|----
(C)  (R) (TM)
----
| (C) (R) (TM)

a|----
&#169; &#174; &#8482;
----
| &#169; &#174; &#8482;

a|----
-> => <- <= 
----
|-> => <- <=

a|----
&rarr; &rArr; &larr; &lArr;
----
|&rarr; &rArr; &larr; &lArr;

a|----
&hearts; &clubs; &diams; &spades;
----
|&hearts; &clubs; &diams; &spades;

a|----
{pp} {plus} {deg} {cpp}
----
|{pp} {plus} {deg} {cpp}
|===

* See https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references[Character Reference Guide]
* See https://docs.asciidoctor.org/asciidoc/latest/attributes/character-replacement-ref/[AsciiDoc Character Replacement Attributes]

==== Menu, Button & Keyboard Macro

NOTE: You need to enable the `experimental` attribute in AsciiDoc

[%header,cols="2,.^2",width=100%]
|===
|Item | Description

a|----
Select menu:File[View > Zoom > 150%]
----
| Select menu:File[View > Zoom > 150%]

a|----
Press the btn:[OK] button when you are finished
----
| Press the btn:[OK] button when you are finished

a|----
Press kbd:[Ctrl+Alt+Delete] to log out
----
| Press kbd:[Ctrl+Alt+Delete] to log out
|===


==== Font size adjustment
_Depreciated_

[.big]#We will teach our twisted speech#

[.small]#To the young believers#

[.big]#We will train our blue-eyed men#

[.small]#To be young believers#

NOTE: [%collapsible] does not work in Antora

[%collapsible]
.View the syntax
====
----
[.big]#We will teach our twisted speech#

[.small]#To the young believers#

[.big]#We will train our blue-eyed men#

[.small]#To be young believers#
----
====

* https://docs.asciidoctor.org/asciidoc/latest/text/custom-inline-styles/[Custom Styles]
* https://docs.asciidoctor.org/asciidoc/latest/text/troubleshoot-unconstrained-formatting/[Unconstrained Pairs]

==== Comments
----
// A single-line comment.
----

----
////
A block comment.

Comments, comments, comments
////
----


=== Apostrophes and Quotes

[%header,cols="2,.^2",width=100%]
|===
|Item | Description

a|----
“The horror! The horror!” 
----
| “The horror! The horror!” 

a|----
'The horror! The horror!'
----
| 'The horror! The horror!'

a|----
"\n\t" and '\n\t'
----
| "\n\t" and '\n\t'

a|----
"`Joseph Conrad’s “Heart of Darkness.”`"
----
| "`Joseph Conrad’s “Heart of Darkness.”`"

a|----
Conrad’s and Conrad\’s 
----
| Conrad’s and Conrad\’s

a|----
``vi```'s my favourite text editor
----
| ``vi```'s my favourite text editor

|===

* See https://docs.asciidoctor.org/asciidoc/latest/text/quotation-marks-and-apostrophes/[Asciidoctor Docs] for details



